---
- name: installing the webserver
  hosts: Test
  become: yes
  gather_facts: no
  tasks:
     - name: Installing the httpd package
       yum:
         name: "{{NAME}}"
         state: latest
     - name: starting the service of httpd
       service:
         name: "{{NAME}}"
         state: started

