---
- name: demo on find the files
  hosts: DEV
  tasks:
     - name: finding the files
       find: 
         paths: /home/anil
         patterns: '*.log'
       register: output
     - name: printing the files
       debug:
         msg: "{{output}}"
     - name: deleting the files
       file:
         path: "{{item.path}}"
         state: absent
       loop:
         "{{output.files}}"
